<script setup lang="ts" generic="TMeta extends Record<string, unknown> = Record<string, unknown>">
/**
 * `<CoarMonthView>` — month grid (6 × 7), pagination mode.
 *
 * Public surface: ONE prop, `:builder`. All config and handlers
 * are routed through the builder — events, locale, timezone,
 * density, canDrop, renderers, etc. The builder also owns the
 * cursor (via `_dateRef()`), which lets `<CoarCalendar>` and the
 * standalone `useMonthView()` share the same wiring.
 *
 * Internal pieces:
 *   - `<CoarMonthGrid>` — sticky weekday header + rows container
 *   - `<CoarMonthRow>` — one week row (7-col grid + bars overlay)
 *   - `<CoarMonthCell>` — day-cell wrapper + pills slot + "+N" button
 *   - `<CoarMonthDayOverlay>` — the day sheet "+N" opens over the cell
 *   - `<CoarMonthPill>` / `<CoarMonthBar>` — event visuals
 *   - `useMonthDnd` — drag/drop glue (preview + ghost + keyboard)
 *   - `useMonthGeometry` — fixed per-density row heights
 *   - `useMonthDayOverlay` — day-sheet open / position state
 *
 * Overflow follows the iOS calendar: a Details cell shows at most
 * `maxEventsPerCell` pills and folds the rest into one "+N" row;
 * Stacked (2 marks) and Compact (6 segments) cap silently. Multi-day
 * bars get at most `monthMaxVisibleLanes` lanes per week row; bars
 * past the cap leave the band and count into the "+N" of every day
 * they cover. Cells never scroll and rows never grow past base +
 * capped lanes. On the web the "+N" row is a button: it opens a sheet
 * over that one cell listing every event of the day — multi-day
 * events first, then the single-day pills — scrolling when long, each
 * entry draggable to another day exactly like a pill in the grid. A
 * tap on the cell body still routes to `onDateClick`.
 *
 * Slot priority for events:
 *   template slot (#pill / #multiDayBar / #event)
 *     → variant-specific renderer (state.pillRenderer / barRenderer)
 *     → universal `state.eventRenderer`
 *     → built-in default (title text on the variant background)
 */

import { computed, ref, toValue } from 'vue';
import { useI18n, useLocalization } from '@cocoar/vue-localization';
import { useMonthDnd, type MonthEventDropPayload } from '../composables/useMonthDnd';
import { useA11yAnnouncer } from '../composables/useA11yAnnouncer';
import { useMonthGeometry } from '../composables/useMonthGeometry';
import { useMonthMetrics } from '../composables/useMonthMetrics';
import { useMonthDayOverlay } from '../composables/useMonthDayOverlay';
import { useViewWindow } from '../composables/useViewWindow';
import {
  Temporal,
  eventInkColor,
  monthGridDates,
  startOfWeek,
  layoutMonthGrid,
  capMonthCellPills,
  capMonthRowLanes,
  monthCellPillLimit,
  localizedWeekdayNames,
  todayInZone,
  dateKey,
  detectFirstDayOfWeekFromLocale,
  isAllDayEvent,
  isTimedEvent,
  buildFormatOptions,
  type CalendarEvent,
  type MonthMultiDayBar,
  type MonthCellPill,
  type MonthCellPillCap,
  type MonthLayout,
  type MonthRowLaneCap,
} from '../core';
import { CalendarBuilder } from '../builders/calendar-builder';
import { RenderEvent } from '../builders/render-helpers';
import CoarMonthPill from './internal/month/CoarMonthPill.vue';
import CoarMonthBar from './internal/month/CoarMonthBar.vue';
import CoarMonthCell from './internal/month/CoarMonthCell.vue';
import CoarMonthDayOverlay from './internal/month/CoarMonthDayOverlay.vue';
import { originatesFromEvent } from './internal/originatesFromEvent';
import CoarMonthRow from './internal/month/CoarMonthRow.vue';
import CoarMonthGrid from './internal/month/CoarMonthGrid.vue';

// Inlined defineProps argument to avoid vue-tsc TS4025 — the
// script-setup-generic compiler exports `__VLS_export` referencing
// local Props, and a local interface that uses the generic TMeta would
// be flagged as a "private name". Inlining keeps the type local AND
// inside Vue's autogenerated component type.
const props = withDefaults(
  defineProps<{
    builder: CalendarBuilder<TMeta>;
    /** Override used by the continuous month surface. */
    month?: Temporal.PlainYearMonth;
    /** Continuous sections share one visible-window writer in their parent. */
    manageViewWindow?: boolean;
    /** Render only the weeks belonging to this month; neighbour dates become blanks. */
    continuousSection?: boolean;
  }>(),
  {
    month: undefined,
    manageViewWindow: true,
    continuousSection: false,
  },
);
const { t } = useI18n();

const slots = defineSlots<{
  /** Render a single-day pill. Falls back through the builder
   *  renderers to a bare title rendering. */
  pill?(props: { event: CalendarEvent<TMeta>; pill: MonthCellPill<TMeta> }): unknown;
  /** Render a multi-day bar. Falls back through the builder
   *  renderers to a bare title rendering. */
  multiDayBar?(props: { event: CalendarEvent<TMeta>; bar: MonthMultiDayBar<TMeta> }): unknown;
}>();

// ─── Builder bindings ────────────────────────────────────────────────
// Snapshot adapter — resolves every `MaybeRefOrGetter` field through
// `toValue` per Vue tick so templates can read `state.value.X` directly.
const state = computed(() => {
  const s = props.builder.state;
  return {
    // Phase 4: read via api.getVisibleEvents() so events from
    // `events()` / `eventsLoader()` AND expanded occurrences from
    // `series()` / `seriesLoader()` all reach the layout. Reading
    // `s.events` directly would skip the recurrence + loader caches.
    events: props.builder.api.getVisibleEvents(),
    timezone: toValue(s.timezone),
    locale: toValue(s.locale),
    firstDayOfWeek: toValue(s.firstDayOfWeek),
    shadeWeekends: toValue(s.shadeWeekends),
    selectedDate: toValue(s.selectedDate),
    density: toValue(s.density),
    monthDensity: toValue(s.monthDensity),
    dateStyle: toValue(s.dateStyle),
    timeStyle: toValue(s.timeStyle),
    hour12: toValue(s.hour12),
    dstPolicy: toValue(s.dstPolicy),
    canDrop: s.canDrop,
    eventRenderer: s.eventRenderer,
    eventTextContrast: toValue(s.eventTextContrast),
    maxEventsPerCell: toValue(s.maxEventsPerCell),
    monthMaxVisibleLanes: toValue(s.monthMaxVisibleLanes),
  };
});
const cursor = computed(() => props.builder.state.date.value);
// Article 9: locale priority — explicit builder.locale() wins, then
// the host app's @cocoar/vue-localization service (so a global
// locale toggle reaches sub-views in standalone usage), finally
// 'en-US' as the last-ditch default.
const localization = useLocalization();
const effectiveLocale = computed<string>(
  () => state.value.locale ?? localization?.language.value ?? 'en-US',
);
const effectiveTimezone = computed(() => state.value.timezone);
const effectiveFirstDayOfWeek = computed(
  () => state.value.firstDayOfWeek ?? detectFirstDayOfWeekFromLocale(effectiveLocale.value),
);

// ─── Visible-range pipeline ──────────────────────────────────────────
// Push the visible window into the builder so loaders / onRangeChange /
// api.getVisibleRange() see a non-null window in standalone usage.
// The composer (`<CoarCalendar>`) does this inline; sub-views go
// through this composable so loader-mode works identically whether
// embedded or standalone.
if (props.manageViewWindow) useViewWindow(props.builder, { view: 'month' });

// ─── Grid + layout ───────────────────────────────────────────────────

const yearMonth = computed(() => {
  if (props.month) return props.month;
  const cur = Temporal.PlainDate.from(cursor.value);
  return Temporal.PlainYearMonth.from({ year: cur.year, month: cur.month });
});

const monthStart = computed(() => yearMonth.value.toPlainDate({ day: 1 }));
const monthEnd = computed(() => yearMonth.value.toPlainDate({ day: yearMonth.value.daysInMonth }));
const gridDates = computed(() => {
  if (!props.continuousSection) {
    return monthGridDates(yearMonth.value, effectiveFirstDayOfWeek.value);
  }
  const first = startOfWeek(monthStart.value, effectiveFirstDayOfWeek.value);
  const lastWeekStart = startOfWeek(monthEnd.value, effectiveFirstDayOfWeek.value);
  const dayCount = first.until(lastWeekStart.add({ days: 7 }), { largestUnit: 'days' }).days;
  return Array.from({ length: dayCount }, (_, index) => first.add({ days: index }));
});

const weekdayHeaders = computed(() =>
  localizedWeekdayNames(effectiveLocale.value, effectiveFirstDayOfWeek.value, 'short'),
);

// ─── Drag & Drop ─────────────────────────────────────────────────────

const rootEl = ref<HTMLElement | null>(null);
const gridRef = ref<HTMLElement | null>(null);
function setGridEl(el: HTMLElement | null) {
  gridRef.value = el;
}

const {
  dnd,
  workingEvents,
  dragSourceSnapshot,
  invalidMonthGhost,
  isPreviewId,
  isInvalidPillTarget,
  onMonthEventPointerdown,
  onMonthEventKeydown,
  keyboardDrag,
} = useMonthDnd({
  events: () => state.value.events,
  gridDates,
  gridRef,
  timezone: () => effectiveTimezone.value,
  // Article 5: forward dstPolicy (was a documented no-op at the
  // view layer until Phase 8.14-D1).
  dstPolicy: () => state.value.dstPolicy,
  canDrop: state.value.canDrop ?? undefined,
  onEventClick: (event, native) => {
    if (native) props.builder.state.onEventClick?.({ event, native });
  },
  onEventDrop: (payload) => props.builder.state.onEventDrop?.(payload),
  onAnnounce: (kind, payload) => onA11yAnnounce(kind, payload),
});

// ─── A11y live-region ────────────────────────────────────────────────

const a11y = useA11yAnnouncer();

/**
 * Aria-label for the preview-ghost variant during a keyboard
 * drag — tells the SR user the keys they have. Without this,
 * the focused ghost would carry the pre-drag aria-label and
 * the user wouldn't know they're in staging mode.
 */
function kbdPreviewAriaLabel(event: CalendarEvent<TMeta>): string {
  const meta = event.meta as { title?: unknown } | undefined;
  const rawTitle = typeof meta?.title === 'string' ? meta.title : undefined;
  const title = rawTitle ?? t('coar.calendar.a11y.unnamedEvent', undefined, 'Event');
  return t(
    'coar.calendar.a11y.kbdPreviewLabel',
    { title },
    `${title} preview — Arrow keys to move, Enter to commit, Escape to cancel`,
  );
}

function eventTitleSafe(event: CalendarEvent<TMeta>): string {
  const meta = event.meta as { title?: unknown } | undefined;
  return typeof meta?.title === 'string'
    ? meta.title
    : t('coar.calendar.a11y.unnamedEvent', undefined, 'Event');
}

function formatAnnouncementWhen(payload: MonthEventDropPayload<TMeta>): string {
  try {
    const fmt = new Intl.DateTimeFormat(
      effectiveLocale.value,
      buildFormatOptions(
        { weekday: 'short', day: 'numeric', month: 'short', timeZone: 'UTC' },
        {
          dateStyle: state.value.dateStyle,
          hour12: state.value.hour12,
        },
      ),
    );
    const d = new Date(payload.target.date + 'T00:00:00Z');
    return fmt.format(d);
  } catch {
    return payload.target.date;
  }
}

function onA11yAnnounce(
  kind: 'committed' | 'cancelled',
  payload?: MonthEventDropPayload<TMeta>,
): void {
  if (kind === 'cancelled') {
    a11y.announce(t('coar.calendar.a11y.moveCancelled', undefined, 'Move cancelled'));
    return;
  }
  if (!payload) return;
  const title = eventTitleSafe(payload.event);
  const when = formatAnnouncementWhen(payload);
  a11y.announce(t('coar.calendar.a11y.eventMovedTo', { title, when }, `${title} moved to ${when}`));
}

const layout = computed<MonthLayout<TMeta>>(() =>
  layoutMonthGrid(workingEvents.value, {
    gridDates: gridDates.value,
    timezone: effectiveTimezone.value,
    ...(props.continuousSection
      ? { visibleStart: monthStart.value, visibleEnd: monthEnd.value }
      : {}),
  }),
);

// ─── Decoration ──────────────────────────────────────────────────────

const today = ref<Temporal.PlainDate>(todayInZone(effectiveTimezone.value));

function isToday(d: Temporal.PlainDate): boolean {
  return Temporal.PlainDate.compare(d, today.value) === 0;
}
function isSelected(d: Temporal.PlainDate): boolean {
  const selected = state.value.selectedDate;
  return selected !== null && Temporal.PlainDate.compare(d, selected) === 0;
}
function isOtherMonth(d: Temporal.PlainDate): boolean {
  return d.year !== yearMonth.value.year || d.month !== yearMonth.value.month;
}
function isWeekend(d: Temporal.PlainDate): boolean {
  // Temporal: 1..7 = Mon..Sun
  return d.dayOfWeek === 6 || d.dayOfWeek === 7;
}

// ─── Row geometry ────────────────────────────────────────────────────

// Measured in the host's styling so a restyled day-number row or a
// taller pill never clips the "+N" row (see `useMonthMetrics`).
const monthMetrics = useMonthMetrics({ rootRef: rootEl, trigger: layout });
const { BAR_HEIGHT, DAY_NUMBER_HEIGHT, barTopPx, rowBarHeightsPx, rowHeightPx } = useMonthGeometry({
  layout,
  monthDensity: () => state.value.monthDensity,
  maxLanes: () => state.value.monthMaxVisibleLanes,
  metrics: monthMetrics,
  maxEventsPerCell: () => state.value.maxEventsPerCell,
});

// ─── Lane cap + folded bars ──────────────────────────────────────────

/** Per row: bars the band shows, bars folded away, hidden count per column. */
const rowLaneCaps = computed<ReadonlyArray<MonthRowLaneCap<TMeta>>>(() =>
  layout.value.weekRows.map((row) =>
    capMonthRowLanes(row.multiDayBars, state.value.monthMaxVisibleLanes),
  ),
);

/** Row index + column of a day in the grid, or `null` off-grid. */
function rowColOf(day: Temporal.PlainDate): { rowIdx: number; col: number } | null {
  const key = dateKey(day);
  const rows = layout.value.weekRows;
  for (let rowIdx = 0; rowIdx < rows.length; rowIdx++) {
    const col = rows[rowIdx].days.findIndex((d) => dateKey(d) === key);
    if (col >= 0) return { rowIdx, col };
  }
  return null;
}
function hiddenBarCountFor(day: Temporal.PlainDate): number {
  const at = rowColOf(day);
  return at ? (rowLaneCaps.value[at.rowIdx]?.hiddenPerColumn[at.col] ?? 0) : 0;
}
/** Every multi-day bar covering the day, visible ones first — the sheet's head. */
function barsCoveringDay(day: Temporal.PlainDate): ReadonlyArray<MonthMultiDayBar<TMeta>> {
  const at = rowColOf(day);
  if (!at) return [];
  const cap = rowLaneCaps.value[at.rowIdx];
  const covers = (b: MonthMultiDayBar<TMeta>) => b.startCol <= at.col && b.endCol >= at.col;
  return [...cap.visible.filter(covers), ...cap.hidden.filter(covers)];
}

// ─── Pill cap + "+N" overflow ────────────────────────────────────────

const pillLimit = computed(() =>
  monthCellPillLimit(state.value.monthDensity, state.value.maxEventsPerCell),
);

const EMPTY_CAP: MonthCellPillCap<TMeta> = { visible: [], hidden: 0 };

/**
 * Per-cell split into rendered pills and the "+N" count. A drag
 * preview landing in a full cell takes the last visible slot so
 * the user always sees where the drop will go; the folded count
 * still reflects the real events behind the marker.
 */
const pillCapsByDayKey = computed<Map<string, MonthCellPillCap<TMeta>>>(() => {
  const out = new Map<string, MonthCellPillCap<TMeta>>();
  for (const row of layout.value.weekRows) {
    for (const day of row.days) {
      const key = dateKey(day);
      const pills = row.cellPills.get(key) ?? [];
      const cap = capMonthCellPills(pills, pillLimit.value);
      const preview = cap.hidden > 0 ? pills.find((p) => isPreviewId(p.event.id)) : undefined;
      if (preview && !cap.visible.includes(preview) && cap.visible.length > 0) {
        out.set(key, {
          visible: [...cap.visible.slice(0, cap.visible.length - 1), preview],
          hidden: cap.hidden,
        });
      } else {
        out.set(key, cap);
      }
    }
  }
  return out;
});

function pillCapFor(day: Temporal.PlainDate): MonthCellPillCap<TMeta> {
  return pillCapsByDayKey.value.get(dateKey(day)) ?? EMPTY_CAP;
}
function visiblePillsFor(day: Temporal.PlainDate): ReadonlyArray<MonthCellPill<TMeta>> {
  return pillCapFor(day).visible;
}
/** Every pill of the day, uncapped — the day sheet's list. */
function pillsFor(day: Temporal.PlainDate): ReadonlyArray<MonthCellPill<TMeta>> {
  const key = dateKey(day);
  for (const row of layout.value.weekRows) {
    const pills = row.cellPills.get(key);
    if (pills) return pills;
  }
  return [];
}
/**
 * "+N" is a Details-only row, as on iOS: Stacked marks and the
 * Compact capsule carry no titles, so the day has to be opened
 * anyway — and their 68 / 52 px rows have no room for a marker.
 * Counts folded single-day pills AND multi-day bars past the lane
 * cap that cover this day.
 */
function overflowCountFor(day: Temporal.PlainDate): number {
  if (state.value.monthDensity !== 'details') return 0;
  return pillCapFor(day).hidden + hiddenBarCountFor(day);
}
function overflowLabelFor(count: number): string {
  return t('coar.calendar.month.moreEvents', { count }, `${count} more events`);
}

// ─── Day sheet ("+N" click) ──────────────────────────────────────────

const overlayRef = ref<InstanceType<typeof CoarMonthDayOverlay> | null>(null);
const dayOverlay = useMonthDayOverlay({
  rootRef: rootEl,
  gridRef,
  overlayEl: () => overlayRef.value?.el ?? null,
  resetToken: yearMonth,
});

const overlayHeadingFormatter = computed(
  () =>
    new Intl.DateTimeFormat(
      effectiveLocale.value,
      buildFormatOptions(
        { weekday: 'short', day: 'numeric', month: 'long', timeZone: 'UTC' },
        { dateStyle: state.value.dateStyle, hour12: state.value.hour12 },
      ),
    ),
);
function overlayHeadingFor(day: Temporal.PlainDate): string {
  return overlayHeadingFormatter.value.format(new Date(Date.UTC(day.year, day.month - 1, day.day)));
}
function overlayLabelFor(day: Temporal.PlainDate): string {
  const date = formatCellAriaLabel(day);
  return t('coar.calendar.month.dayOverlayLabel', { date }, `Events on ${date}`);
}
type SheetEntry<T extends Record<string, unknown>> =
  | { kind: 'live'; pill: MonthCellPill<T> }
  | { kind: 'phantom'; event: CalendarEvent<T> };

/** Pre-drag order of the sheet, so the source phantom can hold its place. */
let sheetOrder: string[] = [];

/**
 * The sheet's rows. At rest: the day's multi-day events (as pills,
 * visible lanes first, folded ones after) followed by the single-day
 * pills in layout order. While one of them is being dragged, the
 * layout has already reflowed without it — the sheet keeps the
 * pre-drag order and shows the source phantom in the dragged entry's
 * slot, so the list does not jump under the pointer.
 */
const sheetEntries = computed<SheetEntry<TMeta>[]>(() => {
  const day = dayOverlay.day.value;
  if (!day) return [];
  const live: MonthCellPill<TMeta>[] = [
    ...barsCoveringDay(day).map((bar, order) => ({ event: bar.event, order: -1000 + order })),
    ...pillsFor(day),
  ];
  const snap = dragSourceSnapshot.value;
  const dragging = snap !== null && sheetOrder.includes(snap.event.id);
  if (!dragging) {
    sheetOrder = live.map((p) => p.event.id);
    return live.map((pill) => ({ kind: 'live', pill }));
  }
  const byId = new Map(live.map((p) => [p.event.id, p] as const));
  const out: SheetEntry<TMeta>[] = [];
  for (const id of sheetOrder) {
    if (id === snap.event.id) out.push({ kind: 'phantom', event: snap.event });
    else {
      const pill = byId.get(id);
      if (pill) {
        out.push({ kind: 'live', pill });
        byId.delete(id);
      }
    }
  }
  // Anything new mid-drag (the preview ghost when the target is this day).
  for (const pill of byId.values()) out.push({ kind: 'live', pill });
  return out;
});
const usesBuiltInCompactCapsule = computed(
  () => state.value.monthDensity === 'compact' && !slots.pill && !state.value.eventRenderer,
);

function eventTitle(event: CalendarEvent<TMeta>): string {
  const meta = event.meta as { title?: unknown } | undefined;
  return typeof meta?.title === 'string' ? meta.title : '(untitled)';
}
function eventColor(event: CalendarEvent<TMeta>): string | undefined {
  const meta = event.meta as { color?: unknown } | undefined;
  return typeof meta?.color === 'string' ? meta.color : undefined;
}
function eventBgFor(event: CalendarEvent<TMeta>): string {
  return (
    eventColor(event) ??
    'var(--coar-calendar-event-default-bg, var(--coar-color-accent-soft, #93c5fd))'
  );
}
function eventBorderFor(event: CalendarEvent<TMeta>): string {
  return eventColor(event) ?? 'var(--coar-color-accent, var(--coar-color-accent-500, #2563eb))';
}

/** Text colour for an event surface — `meta.textColor` or the policy's black/white. */
function eventInkFor(event: CalendarEvent<TMeta>): string {
  const meta = event.meta as { textColor?: unknown } | undefined;
  return eventInkColor({
    background: eventBgFor(event),
    textColor: meta?.textColor,
    policy: state.value.eventTextContrast,
  });
}

/**
 * Locale-formatted screen-reader label for one grid cell.
 * Example: "Wednesday, April 15, 2026". The cell carries it as
 * `aria-label` on its `role="gridcell"` element.
 */
const cellAriaFormatter = computed(
  () =>
    new Intl.DateTimeFormat(
      effectiveLocale.value,
      buildFormatOptions(
        {
          weekday: 'long',
          day: 'numeric',
          month: 'long',
          year: 'numeric',
          timeZone: 'UTC',
        },
        {
          dateStyle: state.value.dateStyle,
          hour12: state.value.hour12,
        },
      ),
    ),
);
function formatCellAriaLabel(day: Temporal.PlainDate): string {
  return cellAriaFormatter.value.format(new Date(Date.UTC(day.year, day.month - 1, day.day)));
}

/** Screen-reader label for an event in the month grid. */
function eventAriaLabel(event: CalendarEvent<TMeta>): string {
  const title = eventTitle(event);
  const overrides = {
    dateStyle: state.value.dateStyle,
    timeStyle: state.value.timeStyle,
    hour12: state.value.hour12,
  };
  try {
    if (isAllDayEvent(event)) {
      const fmt = new Intl.DateTimeFormat(
        effectiveLocale.value,
        buildFormatOptions(
          { weekday: 'short', day: 'numeric', month: 'short', timeZone: 'UTC' },
          overrides,
        ),
      );
      // `end` is RFC-5545 EXCLUSIVE (C1 contract); the spoken label
      // names the last day the event actually covers, so a Fri–Sun
      // stay reads "Fri – Sun", not "Fri – Mon". Single-day events
      // get just their date — no "Fri – Fri".
      const s = event.start;
      const startD = new Date(Date.UTC(s.year, s.month - 1, s.day));
      const e =
        event.end && Temporal.PlainDate.compare(event.end, s) > 0
          ? event.end.subtract({ days: 1 })
          : s;
      if (e.equals(s)) return `${title}, ${fmt.format(startD)}`;
      const endD = new Date(Date.UTC(e.year, e.month - 1, e.day));
      return `${title}, ${fmt.format(startD)} – ${fmt.format(endD)}`;
    }
    const fmt = new Intl.DateTimeFormat(
      effectiveLocale.value,
      buildFormatOptions(
        {
          weekday: 'short',
          day: 'numeric',
          month: 'short',
          hour: 'numeric',
          minute: '2-digit',
          timeZone: effectiveTimezone.value,
        },
        overrides,
      ),
    );
    if (!isTimedEvent(event)) return title;
    return `${title}, ${fmt.format(new Date(event.start.epochMilliseconds))}`;
  } catch {
    return title;
  }
}

// ─── Live pill bindings (shared by the cell and the day sheet) ──────

type LivePillProps = {
  event: CalendarEvent<TMeta>;
  pill: MonthCellPill<TMeta>;
  variant: 'live' | 'preview';
  kbdActive: boolean;
  bg: string;
  ink: string;
  border: string;
  title: string;
  displayZone: string;
  ariaLabel: string;
  density: 'comfortable' | 'compact' | 'spacious';
};
function livePillProps(pill: MonthCellPill<TMeta>): LivePillProps {
  const event = pill.event;
  const preview = isPreviewId(event.id);
  return {
    event,
    pill,
    variant: preview ? 'preview' : 'live',
    kbdActive: keyboardDrag.value !== null,
    bg: eventBgFor(event),
    ink: eventInkFor(event),
    border: eventBorderFor(event),
    title: eventTitle(event),
    displayZone: effectiveTimezone.value,
    ariaLabel: preview && keyboardDrag.value ? kbdPreviewAriaLabel(event) : eventAriaLabel(event),
    density: state.value.density,
  };
}
function livePillHandlers(event: CalendarEvent<TMeta>) {
  return {
    pointerdown: (e: PointerEvent) => onMonthEventPointerdown(e, event),
    keydown: (e: KeyboardEvent) => onMonthEventKeydown(e, event),
    dblclick: (e: MouseEvent) => props.builder.state.onEventDoubleClick?.({ event, native: e }),
    pointerenter: (e: PointerEvent) => props.builder.state.onEventHover?.({ event, native: e }),
    pointerleave: (e: PointerEvent) =>
      props.builder.state.onEventHoverLeave?.({ event, native: e }),
  };
}

// ─── Click handlers ──────────────────────────────────────────────────

function onCellClick(e: PointerEvent, date: Temporal.PlainDate) {
  // A pill's pointerdown bubbles through its cell — that's an event
  // click (onEventClick), not an empty-cell click.
  if (originatesFromEvent(e)) return;
  props.builder.state.onDateClick?.({ date, native: e });
}
function onCellDblclick(e: MouseEvent, date: Temporal.PlainDate) {
  props.builder.state.onDateDoubleClick?.({ date, native: e });
}

// ─── Phantom stubs for non-interactive pill / bar variants ──────────

const phantomPillStub: MonthCellPill<TMeta> = {
  event: {
    id: '__phantom__',
    start: Temporal.PlainDate.from('1970-01-01'),
  } as CalendarEvent<TMeta>,
  order: 0,
};
const phantomBarStub: MonthMultiDayBar<TMeta> = {
  event: {
    id: '__phantom__',
    start: Temporal.PlainDate.from('1970-01-01'),
  } as CalendarEvent<TMeta>,
  lane: 0,
  laneCount: 1,
  startCol: 0,
  endCol: 0,
  clippedStart: false,
  clippedEnd: false,
};

// ─── Public surface for tests ────────────────────────────────────────

defineExpose({
  /** Snapshot of the current layout — useful for tests. */
  getLayout: () => layout.value,
});
</script>

<template>
  <div
    ref="rootEl"
    class="coar-month-view"
    :class="[
      `coar-month-view--density-${state.density}`,
      `coar-month-view--mode-${state.monthDensity}`,
      {
        'coar-month-view--shade-weekends': state.shadeWeekends,
        'coar-month-view--overlay-open': dayOverlay.day.value !== null,
      },
    ]"
    role="grid"
    :aria-label="t('coar.calendar.month.gridLabel', undefined, 'Month grid')"
    :aria-rowcount="layout.weekRows.length + 1"
    :aria-colcount="7"
  >
    <div class="coar-month-view__a11y-live" role="status" aria-live="polite" aria-atomic="true">
      {{ a11y.message.value }}
    </div>
    <CoarMonthGrid :weekday-headers="weekdayHeaders" :set-rows-el="setGridEl">
      <CoarMonthRow
        v-for="(row, rowIndex) in layout.weekRows"
        :key="row.weekStart.toString()"
        :height-px="rowHeightPx[rowIndex]"
        :density="state.density"
      >
        <CoarMonthCell
          v-for="(day, colIndex) in row.days"
          :key="day.toString()"
          :day="day"
          :day-key="dateKey(day)"
          :is-today="isToday(day)"
          :selected="!(continuousSection && isOtherMonth(day)) && isSelected(day)"
          :is-other-month="isOtherMonth(day)"
          :placeholder="continuousSection && isOtherMonth(day)"
          :is-weekend="isWeekend(day)"
          :pills-margin-top-px="rowBarHeightsPx[rowIndex] - DAY_NUMBER_HEIGHT"
          :overflow-count="overflowCountFor(day)"
          :overflow-label="overflowLabelFor(overflowCountFor(day))"
          :overlay-open="dayOverlay.isOpen(day)"
          :density="state.density"
          :ariaRowIndex="rowIndex + 2"
          :ariaColIndex="colIndex + 1"
          :ariaLabel="formatCellAriaLabel(day)"
          @cell-pointerdown="(e) => onCellClick(e, day)"
          @cell-dblclick="(e) => onCellDblclick(e, day)"
          @overflow-click="(_, d) => dayOverlay.toggle(d)"
        >
          <div
            v-if="usesBuiltInCompactCapsule && visiblePillsFor(day).length"
            class="coar-month-view__segment-capsule"
          >
            <button
              v-for="pill in visiblePillsFor(day)"
              :key="pill.event.id"
              type="button"
              class="coar-month-view__segment"
              :style="{ background: eventBgFor(pill.event) }"
              :aria-label="eventAriaLabel(pill.event)"
              v-on="livePillHandlers(pill.event)"
            />
          </div>
          <CoarMonthPill
            v-for="pill in usesBuiltInCompactCapsule ? [] : visiblePillsFor(day)"
            :key="pill.event.id"
            v-bind="livePillProps(pill)"
            v-on="livePillHandlers(pill.event)"
          >
            <template v-if="$slots.pill || state.eventRenderer" #default="{ event: e, pill: p }">
              <slot v-if="$slots.pill" name="pill" :event="e" :pill="p" />
              <RenderEvent
                v-else-if="state.eventRenderer"
                :renderer="state.eventRenderer"
                :ctx="{ event: e, view: 'month', layout: { kind: 'monthPill', layout: p } }"
              />
            </template>
          </CoarMonthPill>
          <!-- Source phantom for a dragged single-day pill. -->
          <CoarMonthPill
            v-if="
              dragSourceSnapshot &&
              dragSourceSnapshot.bars.length === 0 &&
              dragSourceSnapshot.pillCells.includes(dateKey(day))
            "
            variant="phantom"
            :event="dragSourceSnapshot.event"
            :pill="phantomPillStub"
            :bg="eventBgFor(dragSourceSnapshot.event)"
            :ink="eventInkFor(dragSourceSnapshot.event)"
            :border="eventBorderFor(dragSourceSnapshot.event)"
            :title="eventTitle(dragSourceSnapshot.event)"
            :display-zone="effectiveTimezone"
            :density="state.density"
          />
          <!-- Invalid ghost — flows inline so the dashed outline
               stays inside the cell box at the rightmost column. -->
          <CoarMonthPill
            v-if="isInvalidPillTarget(day) && dnd.draggedEvent.value"
            variant="invalid"
            :event="dnd.draggedEvent.value!"
            :pill="phantomPillStub"
            :bg="eventBgFor(dnd.draggedEvent.value!)"
            :ink="eventInkFor(dnd.draggedEvent.value!)"
            :border="eventBorderFor(dnd.draggedEvent.value!)"
            :title="eventTitle(dnd.draggedEvent.value!)"
            :display-zone="effectiveTimezone"
            :snapping-back="dnd.snappingBack.value"
            :density="state.density"
          />
        </CoarMonthCell>

        <!-- Multi-day bars overlay — lanes past `monthMaxVisibleLanes`
             are folded into the covered cells' "+N" (and day sheets). -->
        <CoarMonthBar
          v-for="bar in rowLaneCaps[rowIndex].visible"
          :key="bar.event.id"
          :event="bar.event"
          :bar="bar"
          :variant="isPreviewId(bar.event.id) ? 'preview' : 'live'"
          :kbd-active="keyboardDrag !== null"
          :bg="eventBgFor(bar.event)"
          :ink="eventInkFor(bar.event)"
          :border="eventBorderFor(bar.event)"
          :title="eventTitle(bar.event)"
          :display-zone="effectiveTimezone"
          :aria-label="
            isPreviewId(bar.event.id) && keyboardDrag
              ? kbdPreviewAriaLabel(bar.event)
              : eventAriaLabel(bar.event)
          "
          :density="state.density"
          :top="barTopPx(bar.lane)"
          :left="`calc(${(bar.startCol / 7) * 100}% + 2px)`"
          :width="`calc(${((bar.endCol - bar.startCol + 1) / 7) * 100}% - 4px)`"
          :height="BAR_HEIGHT"
          :z-index="isPreviewId(bar.event.id) ? 100 : bar.lane + 1"
          :clipped-start="bar.clippedStart"
          :clipped-end="bar.clippedEnd"
          @pointerdown="onMonthEventPointerdown($event, bar.event)"
          @keydown="onMonthEventKeydown($event, bar.event)"
          @dblclick="props.builder.state.onEventDoubleClick?.({ event: bar.event, native: $event })"
          @pointerenter="props.builder.state.onEventHover?.({ event: bar.event, native: $event })"
          @pointerleave="
            props.builder.state.onEventHoverLeave?.({ event: bar.event, native: $event })
          "
          @start-resize="dnd.startMonthResizeStart(bar.event)($event)"
          @end-resize="dnd.startMonthResizeEnd(bar.event)($event)"
        >
          <template
            v-if="$slots.multiDayBar || state.eventRenderer"
            #default="{ event: e, bar: b }"
          >
            <slot v-if="$slots.multiDayBar" name="multiDayBar" :event="e" :bar="b" />
            <RenderEvent
              v-else-if="state.eventRenderer"
              :renderer="state.eventRenderer"
              :ctx="{ event: e, view: 'month', layout: { kind: 'monthBar', layout: b } }"
            />
          </template>
        </CoarMonthBar>

        <!-- Source phantom for a dragged multi-day bar. -->
        <CoarMonthBar
          v-for="snapBar in dragSourceSnapshot && dragSourceSnapshot.bars.length > 0
            ? dragSourceSnapshot.bars.filter((b) => b.rowIndex === rowIndex)
            : []"
          :key="`phantom-${snapBar.startCol}-${snapBar.endCol}`"
          variant="phantom"
          :event="dragSourceSnapshot!.event"
          :bar="phantomBarStub"
          :bg="eventBgFor(dragSourceSnapshot!.event)"
          :ink="eventInkFor(dragSourceSnapshot!.event)"
          :border="eventBorderFor(dragSourceSnapshot!.event)"
          :title="eventTitle(dragSourceSnapshot!.event)"
          :display-zone="effectiveTimezone"
          :density="state.density"
          :top="barTopPx(snapBar.lane)"
          :left="`calc(${(snapBar.startCol / 7) * 100}% + 2px)`"
          :width="`calc(${((snapBar.endCol - snapBar.startCol + 1) / 7) * 100}% - 4px)`"
          :height="BAR_HEIGHT"
          :z-index="snapBar.lane + 1"
          :clipped-start="snapBar.clippedStart"
          :clipped-end="snapBar.clippedEnd"
        />

        <!-- Invalid bar overlay -->
        <CoarMonthBar
          v-if="
            invalidMonthGhost &&
            invalidMonthGhost.rowIndex === rowIndex &&
            invalidMonthGhost.isBar &&
            dnd.draggedEvent.value
          "
          variant="invalid"
          :event="dnd.draggedEvent.value!"
          :bar="phantomBarStub"
          :bg="eventBgFor(dnd.draggedEvent.value!)"
          :ink="eventInkFor(dnd.draggedEvent.value!)"
          :border="eventBorderFor(dnd.draggedEvent.value!)"
          :title="eventTitle(dnd.draggedEvent.value!)"
          :display-zone="effectiveTimezone"
          :snapping-back="dnd.snappingBack.value"
          :density="state.density"
          :top="barTopPx(0)"
          :left="`calc(${(invalidMonthGhost.startCol / 7) * 100}% + 2px)`"
          :width="`calc(${((invalidMonthGhost.endCol - invalidMonthGhost.startCol + 1) / 7) * 100}% - 4px)`"
          :height="BAR_HEIGHT"
          :z-index="100"
        />
      </CoarMonthRow>
    </CoarMonthGrid>

    <!-- Day sheet: every single-day event of the "+N" cell, over that
         cell only. Pills carry the grid's own drag / keyboard wiring,
         so an event can be dragged out of the sheet onto any day. -->
    <CoarMonthDayOverlay
      v-if="dayOverlay.day.value"
      ref="overlayRef"
      :day-number="dayOverlay.day.value.day"
      :heading="overlayHeadingFor(dayOverlay.day.value)"
      :label="overlayLabelFor(dayOverlay.day.value)"
      :close-label="t('coar.calendar.month.dayOverlayClose', undefined, 'Close')"
      :is-today="isToday(dayOverlay.day.value)"
      :top="dayOverlay.position.value.top"
      :left="dayOverlay.position.value.left"
      :width="dayOverlay.position.value.width"
      :max-list-height="dayOverlay.position.value.maxListHeight"
      @close="dayOverlay.close()"
    >
      <template
        v-for="entry in sheetEntries"
        :key="entry.kind === 'live' ? entry.pill.event.id : `phantom-${entry.event.id}`"
      >
        <CoarMonthPill
          v-if="entry.kind === 'live'"
          v-bind="livePillProps(entry.pill)"
          v-on="livePillHandlers(entry.pill.event)"
        >
          <template v-if="$slots.pill || state.eventRenderer" #default="{ event: e, pill: p }">
            <slot v-if="$slots.pill" name="pill" :event="e" :pill="p" />
            <RenderEvent
              v-else-if="state.eventRenderer"
              :renderer="state.eventRenderer"
              :ctx="{ event: e, view: 'month', layout: { kind: 'monthPill', layout: p } }"
            />
          </template>
        </CoarMonthPill>
        <CoarMonthPill
          v-else
          variant="phantom"
          :event="entry.event"
          :pill="phantomPillStub"
          :bg="eventBgFor(entry.event)"
          :ink="eventInkFor(entry.event)"
          :border="eventBorderFor(entry.event)"
          :title="eventTitle(entry.event)"
          :display-zone="effectiveTimezone"
          :density="state.density"
        />
      </template>
    </CoarMonthDayOverlay>
  </div>
</template>

<style scoped>
/* Visually-hidden live-region — see CoarTimeGrid for the same
   pattern. Read out by assistive tech only. */
.coar-month-view__a11y-live {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
  white-space: nowrap;
  border: 0;
}

.coar-month-view {
  /* Containing block for the day sheet, which is positioned over
     one cell and scrolls with the surface. */
  position: relative;
  display: flex;
  flex-direction: column;
  background: var(--coar-calendar-bg, #fff);
  /* No outer border / radius — the cell grid already paints its own
     edges. A wrapper "card" frame is the consumer's call: free-floating
     embeds can add `border + border-radius` on the parent; layout-flush
     embeds (most apps) keep the surface flush with their pane edges. */
  /* No `overflow: hidden` here — it would create an inner scroll
     container and capture the weekday-row's sticky positioning,
     stopping it from sticking to the calendar body's actual
     scroll surface. */
  font-family: var(--coar-body-base-family, system-ui, sans-serif);
  font-variant-numeric: tabular-nums;
}
/* While a sheet is open, lift this month above its siblings so a
   sheet reaching past the last row paints over the next section of
   the continuous surface instead of under it. */
.coar-month-view--overlay-open {
  z-index: 10;
}
.coar-month-view:not(.coar-month-view--shade-weekends) :deep(.coar-month-cell--weekend) {
  background: var(--coar-calendar-bg, #fff);
}

/* Apple-style month presentation variants. The event geometry and hit targets
 * stay identical; compact/stacked reduce the visible content to colour marks. */
.coar-month-view--mode-compact :deep(.coar-month-pill),
.coar-month-view--mode-compact :deep(.coar-month-bar) {
  height: 6px !important;
  min-height: 6px;
  border-left-width: 0;
  border-radius: 999px;
  padding: 0;
}

.coar-month-view__segment-capsule {
  display: flex;
  width: 100%;
  height: 6px;
  overflow: hidden;
  border-radius: 999px;
}
.coar-month-view__segment {
  flex: 1 1 0;
  min-width: 3px;
  height: 100%;
  padding: 0;
  border: 0;
  cursor: grab;
}
.coar-month-view__segment + .coar-month-view__segment {
  border-left: 1px solid color-mix(in srgb, white 72%, transparent);
}
.coar-month-view__segment:focus-visible {
  position: relative;
  z-index: 1;
  outline: 2px solid var(--coar-color-focus, #2563eb);
  outline-offset: 1px;
}

.coar-month-view--mode-stacked :deep(.coar-month-pill),
.coar-month-view--mode-stacked :deep(.coar-month-bar) {
  height: 12px !important;
  min-height: 12px;
  border-radius: 4px;
  padding: 0;
}

.coar-month-view--mode-compact :deep(.coar-month-pill__title),
.coar-month-view--mode-compact :deep(.coar-month-bar__title),
.coar-month-view--mode-compact :deep(.coar-event-assignees),
.coar-month-view--mode-stacked :deep(.coar-month-pill__title),
.coar-month-view--mode-stacked :deep(.coar-month-bar__title),
.coar-month-view--mode-stacked :deep(.coar-event-assignees) {
  display: none;
}

/* Slot-fallback text spans (used when consumers don't override
   the `pill` / `multiDayBar` slots and the builder hasn't set a
   pillRenderer / barRenderer / eventRenderer). */
.coar-month-view__pill-title {
  color: var(--coar-text-base, #1a1c1f);
  font-weight: 600;
}
.coar-month-view__bar-title {
  color: var(--coar-text-base, #1a1c1f);
  font-weight: 600;
  text-overflow: ellipsis;
  overflow: hidden;
}
</style>
